export const styles = {
  pageContainer: {
    height: '86vh',
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontFamily: "'Cairo', sans-serif",
    position: 'relative',
    overflow: 'hidden',
    backgroundColor: '#f0f0f0',
  },
  backgroundWrapper: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    backgroundImage: 'url("/logo1.png")',
    backgroundRepeat: 'no-repeat',
    backgroundPosition: 'center center',
    backgroundSize: '85% 165%',
    zIndex: 0,
  },
  blurLayer: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '160%',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
  },

  overlay: {
    backdropFilter: 'blur(10px)',
    backgroundColor: 'rgba(255, 255, 255, 0.75)',
    padding: '30px',
    borderRadius: '20px',
    maxWidth: '450px',
    width: '90%',
    boxShadow: '0 10px 30px rgba(0,0,0,0.2)',
    position: 'relative',
    zIndex: 2,
  },
  formContainer: {
    direction: 'rtl',
    zIndex: 3,
    position: 'relative',
  },
  logoWrapper: {
    textAlign: 'center',
    marginBottom: '40px',
  },
  logo: {
    width: '120px',
    height: '120px',
    borderRadius: '50%',
    objectFit: 'cover',
    boxShadow: '0 4px 8px rgba(0,0,0,0.2)',
  },
  logoText: {
    marginTop: '20px',
    fontSize: '30px',
    fontWeight: 'bold',
    color: '#003c72',
  },
  field: {
    marginBottom: '14px',
  },
  arabicTitle: {
    fontSize: '30px',
    fontWeight: 'bold',
    color: '#455f28',
    marginBottom: '0px',
  },
  englishTitle: {
    fontSize: '16px',
    fontWeight: 'bold',
    color: '#247d80',
    marginTop: '5px',
    marginBottom: '25px',
  },
  label: {
    fontSize: '15px',
    fontWeight: '500',
    color: '#222',
    marginBottom: '6px',
    display: 'block',
  },
  input: {
    width: '100%',
    padding: '12px',
    border: '1px solid #ccc',
    borderRadius: '10px',
    fontSize: '15px',
    boxSizing: 'border-box',
    transition: 'all 0.3s ease',
  },
  togglePassword: {
    marginTop: '10px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: '5px',
  },
  button: {
    width: '100%',
    padding: '12px',
    background: 'linear-gradient(to left, #1e90ff, #004e92)',
    color: 'white',
    fontWeight: 'bold',
    fontSize: '17px',
    border: 'none',
    borderRadius: '12px',
    cursor: 'pointer',
    transition: 'transform 0.2s ease, background 0.3s ease',
  },
  loadingMessage: {
    marginTop: '15px',
    textAlign: 'center',
    fontSize: '16px',
    fontWeight: 'bold',
    color: '#004e92',
  },
};
